# Generated by Django 6.0.4 on 2026-05-14 00:59

import apps.usuarios.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atractivos', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('nickname', models.CharField(max_length=150, unique=True)),
                ('roles', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['nickname'],
            },
            managers=[
                ('objects', apps.usuarios.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_guardado', models.DateField(auto_now_add=True)),
                ('atractivo_turistico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='atractivos.atractivoturistico')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='usuarios.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_visita', to='usuarios.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroModificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('CREACION', 'Creacion'), ('ACTUALIZACION', 'Actualizacion'), ('ELIMINACION', 'Eliminacion'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('OTRA', 'Otra')], default='OTRA', max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('atractivo_turistico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_modificacion', to='atractivos.atractivoturistico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_modificacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveSmallIntegerField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True)),
                ('atractivo_turistico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='atractivos.atractivoturistico')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='usuarios.perfil')),
            ],
        ),
    ]
