# Generated by Django 6.0.4 on 2026-05-20 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtractivoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('nivel_accesibilidad', models.CharField(choices=[('LIBRE', 'Libre'), ('RESTRINGIDO', 'Restringido'), ('PAGADO', 'Pagado')], default='LIBRE', max_length=20)),
                ('estado_conservacion', models.CharField(choices=[('CONSERVADO', 'Conservado'), ('ALTERADO', 'Alterado'), ('EN_DETERIORO', 'En deterioro'), ('DETERIORADO', 'Deteriorado')], default='CONSERVADO', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('nivel_dificultad', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('nivel', models.CharField(choices=[('CATEGORIA', 'Categoria'), ('TIPO', 'Tipo'), ('SUBTIPO', 'Subtipo')], default='CATEGORIA', max_length=20)),
                ('atractivo_turistico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones', to='atractivos.atractivoturistico')),
            ],
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('institucion', models.CharField(max_length=255)),
                ('es_administrador_publico', models.BooleanField(default=True)),
                ('cargo', models.CharField(max_length=255)),
                ('atractivo_turistico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gerente', to='atractivos.atractivoturistico')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo_horario', models.CharField(choices=[('NORMAL', 'Normal'), ('FIN_SEMANA', 'Fin de semana'), ('FERIADO', 'Feriado'), ('ESPECIAL', 'Especial')], default='NORMAL', max_length=20)),
                ('atractivo_turistico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='atractivos.atractivoturistico')),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('atractivo_turistico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='atractivos.atractivoturistico')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('esta_disponible', models.BooleanField(default=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('atractivo_turistico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='atractivos.atractivoturistico')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('altitud', models.FloatField(blank=True, null=True)),
                ('atractivo_turistico', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicacion', to='atractivos.atractivoturistico')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='InformacionClimatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clima', models.CharField(max_length=128)),
                ('temperatura_minima', models.IntegerField()),
                ('temperatura_maxima', models.IntegerField()),
                ('precipitacion_minima', models.IntegerField()),
                ('precipitacion_maxima', models.IntegerField()),
                ('ubicacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informacion_climatica', to='atractivos.ubicacion')),
            ],
            options={
                'verbose_name': 'Información Climática',
                'verbose_name_plural': 'Informaciones Climáticas',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle_principal', models.CharField(max_length=255)),
                ('calle_transversal', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=32)),
                ('referencia', models.TextField(blank=True)),
                ('ubicacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='direccion', to='atractivos.ubicacion')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='DetalleRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('BUENA', 'Buena'), ('REGULAR', 'Regular'), ('MALA', 'Mala'), ('CERRADA', 'Cerrada')], default='BUENA', max_length=20)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('atractivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_ruta', to='atractivos.atractivoturistico')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_ruta', to='atractivos.ruta')),
            ],
            options={
                'unique_together': {('ruta', 'atractivo')},
            },
        ),
    ]
