# Generated by Django 5.1.5 on 2026-05-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('fecha_subida', models.DateField(auto_now_add=True)),
                ('tipo_recurso', models.CharField(choices=[('IMAGEN', 'Imagen'), ('VIDEO', 'Video'), ('DOCUMENTO', 'Documento'), ('INFOGRAFIA', 'Infografia')], max_length=20)),
            ],
            options={
                'ordering': ['-fecha_subida', 'titulo'],
            },
        ),
    ]
