# Generated by Django 6.0.4 on 2026-05-20 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atractivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('fecha_subida', models.DateField(auto_now_add=True)),
                ('tipo_recurso', models.CharField(choices=[('IMAGEN', 'Imagen'), ('VIDEO', 'Video'), ('DOCUMENTO', 'Documento'), ('INFOGRAFIA', 'Infografia')], max_length=20)),
                ('atractivo_turistico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='atractivos.atractivoturistico')),
            ],
        ),
    ]
